%YAML 1.1
---
language: python
python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -r test-requirements.txt
  - pip install -e .
script: nosetests
after_success:
  - codecov
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    python: 3.4
    tags: true
    all_branches: true
  user: sprockets
  password:
    secure: [REPLACE-ME]
